services:
  api:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: "tron_api"
    env_file: src/.env
    environment:
      DB_HOST: database
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    container_name: "tron_postgres-db"
    env_file: src/.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "10145:5432"